// Package skillgen renders a Claude Code Agent Skill (SKILL.md) from a cobra
// command tree. Generating from the live command tree keeps the skill in sync
// with gh-wheel's actual commands and flags.
package skillgen

import (
	"fmt"
	"sort"
	"strings"

	"github.com/spf13/cobra"
	"github.com/spf13/pflag"
	"gopkg.in/yaml.v3"
)

// Options controls SKILL.md generation.
type Options struct {
	// Name is the skill name, used for the frontmatter `name` field and the
	// output directory. Defaults to "gh-wheel" when empty.
	Name string
	// Description overrides the frontmatter `description`. When empty it is
	// derived from the root command's Short text.
	Description string
}

// skipCommands are cobra built-ins and meta commands excluded from the skill:
// help/completion are generated by cobra, and skill is the generator itself.
var skipCommands = map[string]bool{
	"help":       true,
	"completion": true,
	"skill":      true,
}

// Generate renders a SKILL.md for the gh-wheel command tree rooted at root.
func Generate(root *cobra.Command, opts Options) string {
	name := opts.Name
	if name == "" {
		name = "gh-wheel"
	}
	desc := strings.TrimSpace(opts.Description)
	if desc == "" {
		desc = deriveDescription(root)
	}
	desc = strings.ReplaceAll(desc, "\n", " ")

	var b strings.Builder

	// Frontmatter — marshalled via yaml.v3 so descriptions containing
	// YAML-sensitive characters (#, :, quotes, …) stay valid YAML.
	fm := struct {
		Name        string `yaml:"name"`
		Description string `yaml:"description"`
	}{Name: name, Description: desc}
	fmBytes, err := yaml.Marshal(fm)
	if err != nil {
		// yaml.Marshal of two strings cannot realistically fail; fall back to a
		// minimal valid frontmatter rather than emitting nothing.
		fmBytes = []byte(fmt.Sprintf("name: %q\ndescription: %q\n", name, desc))
	}
	b.WriteString("---\n")
	b.Write(fmBytes)
	b.WriteString("---\n\n")

	// Title and overview.
	fmt.Fprintf(&b, "# %s\n\n", name)
	if long := strings.TrimSpace(root.Long); long != "" {
		fmt.Fprintf(&b, "%s\n\n", long)
	} else if root.Short != "" {
		fmt.Fprintf(&b, "%s\n\n", root.Short)
	}
	b.WriteString("このスキルは `gh wheel` CLI を操作するためのリファレンスです。" +
		"以下のコマンドを実行して gh-wheel を操作してください。\n\n")

	// Workflows.
	b.WriteString("## ワークフロー\n\n")
	b.WriteString("gh-wheel は2つのロールのワークフローを支援します。\n\n")
	b.WriteString("### 開発者（Developer）ワークフロー\n\n")
	b.WriteString("Issue の内容を確認して PR を作成し、レビューコメントに対応して修正内容を返信で報告する。\n\n")
	b.WriteString("```bash\n")
	b.WriteString("# 1. 自分が関わる PR・Issue を一覧する\n")
	b.WriteString("gh wheel task\n\n")
	b.WriteString("# 2. Issue の依存関係を可視化する\n")
	b.WriteString("gh wheel graph --issue 42\n\n")
	b.WriteString("# 3. PR の未解決レビュースレッドを確認する\n")
	b.WriteString("gh wheel review threads 42\n\n")
	b.WriteString("# 4. レビューコメントへ修正完了を返信する\n")
	b.WriteString("gh wheel review reply 42 --comment-id 123456789 --body \"Fixed in latest commit.\"\n")
	b.WriteString("```\n\n")
	b.WriteString("### レビュアー（Reviewer）ワークフロー\n\n")
	b.WriteString("レビュー依頼された PR に対して AI 支援でレビューを行い、構造化されたレビューを投稿する。\n\n")
	b.WriteString("```bash\n")
	b.WriteString("# 1. レビュー依頼されている PR を一覧する\n")
	b.WriteString("gh wheel task -r\n\n")
	b.WriteString("# 2. AI レビュー用の Markdown プロンプトを生成する\n")
	b.WriteString("gh wheel task prompt 42\n\n")
	b.WriteString("# 3. AI にプロンプトを渡し、出力を review.yaml として保存する\n")
	b.WriteString("# 4. 投稿前にレビューファイルを検証する\n")
	b.WriteString("gh wheel review validate -f review.yaml --pr 42\n\n")
	b.WriteString("# 5. レビューを GitHub に投稿する\n")
	b.WriteString("gh wheel review post 42 -f review.yaml\n")
	b.WriteString("```\n\n")

	// Command reference.
	b.WriteString("## コマンドリファレンス\n\n")
	for _, c := range sortedCommands(root) {
		writeCommand(&b, c)
	}

	// Global flags and notes.
	writeGlobalFlags(&b, root)
	writeNotes(&b, root)

	return b.String()
}

// deriveDescription builds a frontmatter description from the root command.
func deriveDescription(root *cobra.Command) string {
	if root.Short != "" {
		return root.Short + "。task / graph / monitor / review のコマンドで PR・Issue 管理、依存グラフ、レビューを操作する。"
	}
	return "gh-wheel (gh wheel) を操作して Issue-Driven 開発を行う。"
}

// sortedCommands returns parent's available, non-skipped subcommands sorted by
// name for deterministic output.
func sortedCommands(parent *cobra.Command) []*cobra.Command {
	var cmds []*cobra.Command
	for _, c := range parent.Commands() {
		if !c.IsAvailableCommand() || skipCommands[c.Name()] {
			continue
		}
		cmds = append(cmds, c)
	}
	sort.Slice(cmds, func(i, j int) bool { return cmds[i].Name() < cmds[j].Name() })
	return cmds
}

// writeCommand renders c (and its subcommands, recursively) as a markdown
// section. Heading depth tracks the command path depth.
func writeCommand(b *strings.Builder, c *cobra.Command) {
	depth := strings.Count(c.CommandPath(), " ") // "wheel task" → 1, "wheel task close" → 2
	heading := strings.Repeat("#", depth+2)
	fmt.Fprintf(b, "%s `gh %s`\n\n", heading, c.CommandPath())

	if c.Short != "" {
		fmt.Fprintf(b, "%s\n\n", c.Short)
	}
	if long := strings.TrimSpace(c.Long); long != "" && long != c.Short {
		fmt.Fprintf(b, "%s\n\n", long)
	}
	if c.Runnable() {
		fmt.Fprintf(b, "```\ngh %s\n```\n\n", c.UseLine())
	}

	if flags := commandFlags(c); len(flags) > 0 {
		b.WriteString("フラグ:\n\n")
		for _, fl := range flags {
			fmt.Fprintf(b, "- %s\n", fl)
		}
		b.WriteString("\n")
	}

	for _, sub := range sortedCommands(c) {
		writeCommand(b, sub)
	}
}

// commandFlags returns c's local flags, excluding inherited persistent flags
// (documented once in writeGlobalFlags) and the auto-generated help flag.
// LocalFlags already filters out flags inherited from parent commands, so an
// intermediate command's persistent flags are not duplicated onto its children.
func commandFlags(c *cobra.Command) []string {
	var out []string
	c.LocalFlags().VisitAll(func(f *pflag.Flag) {
		if f.Name == "help" || f.Hidden {
			return
		}
		out = append(out, formatFlag(f))
	})
	return out
}

// writeGlobalFlags documents the root persistent flags shared by all commands.
func writeGlobalFlags(b *strings.Builder, root *cobra.Command) {
	var flags []string
	root.PersistentFlags().VisitAll(func(f *pflag.Flag) {
		if f.Name == "help" || f.Hidden {
			return
		}
		flags = append(flags, formatFlag(f))
	})
	if len(flags) == 0 {
		return
	}
	b.WriteString("## グローバルフラグ\n\nすべてのサブコマンドで利用できます。\n\n")
	for _, fl := range flags {
		fmt.Fprintf(b, "- %s\n", fl)
	}
	b.WriteString("\n")
}

// writeNotes appends guidance an agent needs to operate gh-wheel safely. The
// auto-report note is emitted only when the command tree actually exposes the
// --no-report flag, so the generated skill never documents a feature absent
// from this build.
func writeNotes(b *strings.Builder, root *cobra.Command) {
	b.WriteString("## 補足\n\n")
	b.WriteString("- `--json` を付けると機械可読な JSON を stdout に出力します。スクリプトや AI 連携ではこちらを使ってください。\n")
	b.WriteString("- `--jq <式>` で JSON 出力を絞り込めます。\n")
	b.WriteString("- `--repo owner/repo` で対象リポジトリを明示できます（省略時は cwd から検出）。\n")
	if root.PersistentFlags().Lookup("no-report") != nil {
		b.WriteString("- 予期しないエラーや panic が発生すると、対話実行時に gh-wheel への Issue 起票（auto-report）が提案されます。" +
			"`--no-report` または環境変数 `GH_WHEEL_NO_REPORT` で抑止できます。\n")
	}
}

// formatFlag renders a single flag as a markdown list item.
func formatFlag(f *pflag.Flag) string {
	var name string
	if f.Shorthand != "" {
		name = fmt.Sprintf("`-%s, --%s`", f.Shorthand, f.Name)
	} else {
		name = fmt.Sprintf("`--%s`", f.Name)
	}
	usage := f.Usage
	if f.DefValue != "" && f.DefValue != "false" {
		usage = fmt.Sprintf("%s (default %q)", usage, f.DefValue)
	}
	return fmt.Sprintf("%s — %s", name, usage)
}
